const STORE_KEY='steph_jenny_v2_data';
const defaultData={clients:[],interventions:[],machines:[],tarifs:{heure:16,machine:2.5}};
let data=loadData();let currentTab='accueil';
function loadData(){try{const s=localStorage.getItem(STORE_KEY);return s?{...defaultData,...JSON.parse(s)}:structuredClone(defaultData)}catch(e){return structuredClone(defaultData)}}
function saveData(){localStorage.setItem(STORE_KEY,JSON.stringify(data));render()}
function euros(n){return Number(n||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}
function today(){return new Date().toISOString().slice(0,10)}
function niceDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):''}
function monthItems(list,dateField='date'){const now=new Date();return list.filter(x=>{const d=new Date((x[dateField]||today())+'T12:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()})}
function stats(){const inter=monthItems(data.interventions),machines=monthItems(data.machines);const heures=inter.reduce((s,x)=>s+Number(x.heures||0),0);const totalMachines=machines.reduce((s,x)=>s+Number(x.nombre||0),0);const caHeures=heures*Number(data.tarifs.heure||0),caMachines=totalMachines*Number(data.tarifs.machine||0);return{inter,machines,heures,totalMachines,caHeures,caMachines,total:caHeures+caMachines}}
function render(){document.getElementById('app').innerHTML=`<main class="phone"><section class="hero"><div class="hello">🌿 Bonjour Stéphanie</div><h1>Steph & Jenny</h1><div class="brand">GESTION</div><p>${niceDate(today())}</p><small>Version 2 · sauvegarde sur cet appareil</small></section>${currentTab==='accueil'?viewHome():''}${currentTab==='ajouter'?viewAjouter():''}${currentTab==='planning'?viewPlanning():''}${currentTab==='clients'?viewClients():''}${currentTab==='recap'?viewRecap():''}${currentTab==='reglages'?viewReglages():''}<nav class="bottom">${navBtn('accueil','🏠','Accueil')}${navBtn('ajouter','➕','Ajouter')}${navBtn('planning','📅','Plan.')}${navBtn('clients','👥','Clients')}${navBtn('reglages','⚙️','Réglages')}</nav></main>`}
function navBtn(tab,icon,label){return`<button class="${currentTab===tab?'active':''}" onclick="currentTab='${tab}';render()">${icon}<span>${label}</span></button>`}
function viewHome(){const s=stats();const todayInter=data.interventions.filter(x=>x.date===today());return`<button class="primary" onclick="currentTab='ajouter';render()">▶ Commencer une intervention</button><div class="grid"><button onclick="currentTab='clients';render()">👥 Clients</button><button onclick="currentTab='recap';render()">📊 Récapitulatif</button><button onclick="currentTab='planning';render()">📅 Planning</button><button onclick="currentTab='reglages';render()">⚙️ Réglages</button></div><section class="card"><h2>Planning du jour</h2>${todayInter.length?todayInter.map(cardInter).join(''):`<p class="muted">Aucune intervention prévue aujourd'hui.</p>`}</section><section class="card stats"><h2>Ce mois-ci</h2><div><strong>${s.heures.toFixed(2).replace('.',',')}</strong><span>heures</span></div><div><strong>${s.totalMachines}</strong><span>machines</span></div><div><strong>${s.inter.length}</strong><span>interv.</span></div><div><strong>${euros(s.total)}</strong><span>estimé</span></div></section>`}
function viewAjouter(){return`<section class="card"><h2>Ajouter une intervention</h2><label>Date <input id="iDate" type="date" value="${today()}"></label><label>Client <input id="iClient" placeholder="Nom du client"></label><label>Type <select id="iType"><option>Ménage</option><option>Location saisonnière</option><option>Repassage</option><option>Autre</option></select></label><label>Heures <input id="iHeures" type="number" step="0.25" placeholder="ex : 2"></label><label>Notes <textarea id="iNotes" placeholder="Détails de l'intervention"></textarea></label><button class="primary" onclick="addIntervention()">Enregistrer l’intervention</button></section><section class="card"><h2>Ajouter des machines</h2><label>Date <input id="mDate" type="date" value="${today()}"></label><label>Client / Location <input id="mClient" placeholder="Nom"></label><label>Nombre de machines <input id="mNombre" type="number" placeholder="ex : 3"></label><button onclick="addMachine()">Enregistrer les machines</button></section>`}
function val(id){return document.getElementById(id)?.value.trim()||''}
function addIntervention(){const item={id:Date.now(),date:val('iDate'),client:val('iClient'),type:val('iType'),heures:Number(val('iHeures')||0),notes:val('iNotes')};if(!item.client){alert('Indique le nom du client.');return}data.interventions.push(item);if(!data.clients.find(c=>c.nom.toLowerCase()===item.client.toLowerCase()))data.clients.push({id:Date.now()+1,nom:item.client,tel:'',notes:''});saveData();currentTab='accueil';render()}
function addMachine(){const item={id:Date.now(),date:val('mDate'),client:val('mClient'),nombre:Number(val('mNombre')||0)};if(!item.client||!item.nombre){alert('Indique le client et le nombre de machines.');return}data.machines.push(item);saveData();currentTab='recap';render()}
function viewPlanning(){const sorted=[...data.interventions].sort((a,b)=>a.date.localeCompare(b.date));return`<section class="card"><h2>Planning</h2>${sorted.length?sorted.map(cardInter).join(''):'<p class="muted">Aucune intervention enregistrée.</p>'}</section>`}
function cardInter(x){return`<div class="item"><strong>${x.client}</strong><span>${niceDate(x.date)}</span><small>${x.type} · ${x.heures||0} h</small>${x.notes?`<p>${x.notes}</p>`:''}<button class="danger" onclick="removeIntervention(${x.id})">Supprimer</button></div>`}
function removeIntervention(id){data.interventions=data.interventions.filter(x=>x.id!==id);saveData()}
function viewClients(){return`<section class="card"><h2>Clients</h2><label>Nom <input id="cNom" placeholder="Nom du client"></label><label>Téléphone <input id="cTel" placeholder="Téléphone"></label><label>Notes <textarea id="cNotes" placeholder="Adresse, consignes..."></textarea></label><button onclick="addClient()">Ajouter client</button>${data.clients.length?data.clients.map(c=>`<div class="item"><strong>${c.nom}</strong><span>${c.tel||''}</span><p>${c.notes||''}</p><button class="danger" onclick="removeClient(${c.id})">Supprimer</button></div>`).join(''):'<p class="muted">Aucun client pour le moment.</p>'}</section>`}
function addClient(){const c={id:Date.now(),nom:val('cNom'),tel:val('cTel'),notes:val('cNotes')};if(!c.nom){alert('Indique le nom du client.');return}data.clients.push(c);saveData()}
function removeClient(id){data.clients=data.clients.filter(c=>c.id!==id);saveData()}
function viewRecap(){const s=stats();return`<section class="card"><h2>Récapitulatif du mois</h2><div class="recap"><span>Heures</span><strong>${s.heures.toFixed(2).replace('.',',')} h</strong></div><div class="recap"><span>Machines</span><strong>${s.totalMachines}</strong></div><div class="recap"><span>Montant heures</span><strong>${euros(s.caHeures)}</strong></div><div class="recap"><span>Montant machines</span><strong>${euros(s.caMachines)}</strong></div><div class="recap total"><span>Total estimé</span><strong>${euros(s.total)}</strong></div><button onclick="exportData()">Sauvegarder mes données</button></section><section class="card"><h2>Machines</h2>${data.machines.length?data.machines.map(m=>`<div class="item"><strong>${m.client}</strong><span>${niceDate(m.date)}</span><small>${m.nombre} machine(s) · ${euros(m.nombre*data.tarifs.machine)}</small><button class="danger" onclick="removeMachine(${m.id})">Supprimer</button></div>`).join(''):'<p class="muted">Aucune machine enregistrée.</p>'}</section>`}
function removeMachine(id){data.machines=data.machines.filter(m=>m.id!==id);saveData()}
function viewReglages(){return`<section class="card"><h2>Réglages</h2><label>Tarif horaire (€) <input id="tarifHeure" type="number" step="0.50" value="${data.tarifs.heure}"></label><label>Tarif machine (€) <input id="tarifMachine" type="number" step="0.10" value="${data.tarifs.machine}"></label><button onclick="saveSettings()">Enregistrer les tarifs</button></section><section class="card"><h2>Sauvegarde</h2><button onclick="exportData()">Exporter une sauvegarde</button><label>Importer une sauvegarde <input type="file" accept=".json" onchange="importData(event)"></label></section>`}
function saveSettings(){data.tarifs.heure=Number(val('tarifHeure')||0);data.tarifs.machine=Number(val('tarifMachine')||0);saveData()}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sauvegarde-steph-jenny.json';a.click()}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data={...defaultData,...JSON.parse(reader.result)};saveData();alert('Sauvegarde importée.')}catch(err){alert('Fichier de sauvegarde invalide.')}};reader.readAsText(file)}
render();
