const STORE_KEY="sj_v5_pro_data";
const GOOGLE_CALENDAR_URL="https://calendar.google.com/calendar/u/0/r";
const DEFAULT_CLIENTS=[
 "Nadège","Camille & Benoît","Thierry","Serge","Hélène","Juliette","Céline","Cabinet d'infirmières","Dorothée & Laurent","Élodie","Maryse","Véronique","Jean-Christophe","Nicole","Aymeric","Daniel","Jean-Claude","Richard","Kath","Floriane & Max"
];
const uid=()=>crypto?.randomUUID?crypto.randomUUID():"id"+Date.now()+Math.random();
const defaultDB=()=>({version:"v5-pro",current:null,month:new Date().toISOString().slice(0,7),settings:{hourRate:16,machinePrice:2.5,rounding:"hour"},clients:DEFAULT_CLIENTS.map((name,i)=>({id:uid(),ref:(["Richard","Kath","Floriane & Max"].includes(name)?"G":"C")+String(i+1).padStart(3,"0"),name,phone:"",email:"",address:"",type:["Richard","Kath","Floriane & Max"].includes(name)?"Location saisonnière":"CESU",rate:16,archived:false,notes:""})),interventions:[],planning:[],closures:{}});
let db=load(), screen="home";
function load(){try{return JSON.parse(localStorage.getItem(STORE_KEY))||defaultDB()}catch(e){return defaultDB()}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
const $=q=>document.querySelector(q), pad=n=>String(n).padStart(2,"0");
const fmtDate=s=>new Date(s+"T00:00:00").toLocaleDateString("fr-FR"), fmtTime=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`;
const fmtDur=m=>`${m<0?"-":""}${Math.floor(Math.abs(m)/60)}h${pad(Math.abs(m)%60)}`;
const euros=n=>Number(n||0).toFixed(2).replace(".",",")+" €";
const duration=(a,b)=>{const ms=new Date(b)-new Date(a);return ms>0?Math.max(1,Math.ceil(ms/60000)):0};
const monthItems=()=>db.interventions.filter(x=>x.date?.startsWith(db.month));
function personMinutes(items,who){return items.filter(x=>x.worker==="deux"||x.worker===who).reduce((a,x)=>a+x.duration,0)}
function declaredHours(min){const sign=min<0?-1:1, abs=Math.abs(min), h=Math.floor(abs/60), r=abs%60;return sign*(r>=31?h+1:h)}
function fmtReport(m){return m===0?"0 min":(m>0?"+":"")+m+" min"}
function reportLabel(m){return m<0?`${fmtReport(m)} à déduire`:m>0?`${fmtReport(m)} à ajouter`:"0 min"}
function prevMonth(m){let[y,mo]=m.split("-").map(Number);mo--;if(mo===0){mo=12;y--}return y+"-"+String(mo).padStart(2,"0")}
function ckey(client,month,who){return `${client}|${month}|${who}`}
function carryIn(client,month,who){return db.closures?.[ckey(client,prevMonth(month),who)]?.carryOut||0}
function calcReport(client,month,who,raw){const cin=carryIn(client,month,who), adjusted=raw+cin, declared=declaredHours(adjusted), carryOut=adjusted-declared*60;return{carryIn:cin,adjusted,declared,carryOut}}
function client(name){return db.clients.find(c=>c.name===name)||{name,rate:db.settings.hourRate,type:""}}
function activeClients(){return db.clients.filter(c=>!c.archived)}
function nav(){return `<div class="nav"><button onclick="go('home')">🏠<br>Accueil</button><button onclick="newIntervention()">➕<br>Ajouter</button><button onclick="go('planning')">📅<br>Plan.</button><button onclick="go('clients')">👥<br>Clients</button><button onclick="go('settings')">⚙️<br>Réglages</button></div>`}
function go(s){screen=s;render()}
function layout(content){document.getElementById("app").innerHTML=`<main class="app">${content}${nav()}</main>`}
function render(){({home,clients,planning,summary,payroll,settings,reports,interventions,seasonal}[screen]||home)()}
function home(){
 const items=monthItems(), total=items.reduce((a,x)=>a+x.duration,0), machines=items.filter(x=>x.client==="Floriane & Max").reduce((a,x)=>a+(x.machines||0),0), today=new Date().toISOString().slice(0,10), dayPlan=db.planning.filter(p=>p.date===today).sort((a,b)=>a.time.localeCompare(b.time)), ca=items.reduce((a,x)=>a+(x.duration/60)*(client(x.client).rate||db.settings.hourRate),0)+machines*db.settings.machinePrice;
 layout(`<div class="hero"><div class="muted">🌿 Bonjour Stéphanie</div><div class="logo">Steph & Jenny</div><div class="sub">GESTION V5</div><p>${new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</p><p class="small">Version professionnelle</p></div>
 ${db.current?`<div class="card notice"><p>Intervention en cours</p><h2>${db.current.client}</h2><p>Commencée à ${fmtTime(new Date(db.current.start))}</p><button class="big stop" onclick="stopWork()">⏹ Terminer</button></div>`:`<button class="big" onclick="newIntervention()">▶ Commencer une intervention</button>`}
 <div class="grid"><button onclick="go('clients')">👥 Clients</button><button onclick="go('summary')">📄 Récapitulatif</button><button onclick="go('payroll')">💶 Fiche paie</button><button onclick="go('interventions')">✏️ Modifier heures</button><button onclick="go('seasonal')">🏡 Flo & Max</button><button onclick="window.open('${GOOGLE_CALENDAR_URL}','_blank')">📅 Google Agenda</button></div>
 <div class="card"><h3>Planning du jour</h3>${dayPlan.length?dayPlan.map(p=>`<p><b>${p.time}</b> • ${p.client}<br><span class="small">${p.type} • ${p.worker==="deux"?"À deux":p.worker==="stephanie"?"Stéphanie":"Jennifer"}</span></p>`).join(""):"<p class='small'>Aucune intervention prévue aujourd’hui.</p>"}</div>
 <div class="card"><p>Ce mois-ci</p><div class="grid3"><div class="stat"><strong>${fmtDur(total)}</strong><span>heures</span></div><div class="stat"><strong>${machines}</strong><span>machines Flo & Max</span></div><div class="stat"><strong>${euros(ca)}</strong><span>estimé</span></div></div></div>`);
}
function newIntervention(editId=null){const x=editId?db.interventions.find(i=>i.id===editId):null, opts=activeClients().map(c=>`<option ${x?.client===c.name?"selected":""}>${c.name}</option>`).join("");
 layout(`<button onclick="go('home')">← Retour</button><h2>${x?"Modifier intervention":"Nouvelle intervention"}</h2><input id="editId" type="hidden" value="${x?.id||""}">
 <label>Client</label><select id="client" onchange="toggleMachines()">${opts}</select><label>Qui intervient ?</label><select id="worker"><option value="deux">À deux</option><option value="stephanie">Stéphanie seule</option><option value="jennifer">Jennifer seule</option></select>
 <label>Type</label><select id="type"><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option><option>Linge</option></select>
 <div id="machineBox" class="card notice"><h3>Machines Floriane & Max</h3><p class="small">Les machines sont facturées uniquement à Floriane & Max : ${euros(db.settings.machinePrice)} par machine.</p><label>Nombre de machines</label><input id="machines" type="number" value="${x?.machines||0}"></div>
 <label>Note</label><textarea id="note">${x?.note||""}</textarea>
 <div class="card"><label>Date</label><input id="date" type="date" value="${x?.date||new Date().toISOString().slice(0,10)}"><label>Arrivée</label><input id="start" type="time" value="${x?fmtTime(new Date(x.start)):""}"><label>Départ</label><input id="end" type="time" value="${x?fmtTime(new Date(x.end)):""}"><button class="big blue" onclick="saveManual()">💾 Enregistrer</button></div>
 ${!x?`<button class="big" onclick="startWork()">▶ Démarrer maintenant</button>`:`<button class="stop" style="width:100%;margin-top:10px" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button>`}`);
 if(x){$("#worker").value=x.worker;$("#type").value=x.type||"Ménage"} toggleMachines()
}
function toggleMachines(){const isFlo=$("#client")?.value==="Floriane & Max"; if($("#machineBox"))$("#machineBox").style.display=isFlo?"block":"none";}
function startWork(){db.current={client:$("#client").value,worker:$("#worker").value,type:$("#type").value,machines:$("#client").value==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,start:new Date().toISOString()};save();go('home')}
function stopWork(){const end=new Date().toISOString();db.interventions.push({...db.current,id:uid(),end,date:db.current.start.slice(0,10),duration:duration(db.current.start,end)});db.current=null;save();go('home')}
function saveManual(){const id=$("#editId").value,d=$("#date").value,s=$("#start").value,e=$("#end").value;if(!d||!s||!e)return alert("Il manque la date ou les heures.");const start=new Date(`${d}T${s}:00`).toISOString(),end=new Date(`${d}T${e}:00`).toISOString(),clientName=$("#client").value,obj={id:id||uid(),client:clientName,worker:$("#worker").value,type:$("#type").value,machines:clientName==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,start,end,date:d,duration:duration(start,end)};db.interventions=id?db.interventions.map(x=>x.id===id?obj:x):[...db.interventions,obj];save();go('interventions')}
function interventions(){const items=monthItems().sort((a,b)=>new Date(b.start)-new Date(a.start));layout(`<button onclick="go('home')">← Retour</button><h2>Modifier interventions</h2>${items.map(x=>`<div class="item"><div class="row"><b>${x.client}</b><span class="pill">${fmtDur(x.duration)}</span></div><div>${fmtDate(x.date)} • ${fmtTime(new Date(x.start))} → ${fmtTime(new Date(x.end))}</div><p class="small">${x.type||""} ${x.client==="Floriane & Max"&&x.machines?`• ${x.machines} machine(s)`:""} ${x.note||""}</p><div class="grid"><button onclick="newIntervention('${x.id}')">✏️ Modifier</button><button class="stop" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class='card'>Aucune intervention.</div>"}`)}
function deleteIntervention(id){if(confirm("Supprimer cette intervention ?")){db.interventions=db.interventions.filter(x=>x.id!==id);save();interventions()}}
function clients(){layout(`<button onclick="go('home')">← Retour</button><h2>Clients</h2><button class="big" onclick="clientForm()">➕ Ajouter un client</button>${db.clients.map(c=>`<div class="item"><div class="row"><b>${c.name}</b><span class="pill">${c.archived?"Archivé":c.type}</span></div><p class="small">${c.ref} • ${c.phone||"Tél. non renseigné"}<br>${c.address||"Adresse non renseignée"}</p><div class="grid"><button onclick="clientForm('${c.id}')">✏️ Fiche</button><button onclick="summary('${c.name.replaceAll("'","\\'")}')">📄 Récap</button></div></div>`).join("")}`)}
function clientForm(id=null){const c=id?db.clients.find(x=>x.id===id):{};layout(`<button onclick="go('clients')">← Retour</button><h2>Fiche client</h2><input id="cid" type="hidden" value="${c?.id||""}"><label>Référence</label><input id="ref" value="${c?.ref||""}"><label>Nom</label><input id="name" value="${c?.name||""}"><label>Téléphone</label><input id="phone" value="${c?.phone||""}"><label>Email</label><input id="email" value="${c?.email||""}"><label>Adresse</label><textarea id="address">${c?.address||""}</textarea><label>Type</label><select id="ctype"><option>CESU</option><option>Location saisonnière</option><option>Particulier</option></select><label>Tarif horaire</label><input id="rate" type="number" value="${c?.rate||16}"><label>Notes</label><textarea id="cnotes">${c?.notes||""}</textarea><button class="big" onclick="saveClient()">💾 Enregistrer</button>${c?.id?`<button class="stop" style="width:100%;margin-top:10px" onclick="archiveClient('${c.id}')">📦 Archiver</button>`:""}`);if(c?.type)$("#ctype").value=c.type}
function saveClient(){const id=$("#cid").value,obj={id:id||uid(),ref:$("#ref").value,name:$("#name").value,phone:$("#phone").value,email:$("#email").value,address:$("#address").value,type:$("#ctype").value,rate:+$("#rate").value||16,notes:$("#cnotes").value,archived:false};if(!obj.name)return alert("Nom manquant");db.clients=id?db.clients.map(c=>c.id===id?{...c,...obj}:c):[...db.clients,obj];save();go('clients')}
function archiveClient(id){const c=db.clients.find(c=>c.id===id);if(c){c.archived=true;save();go('clients')}}
function summary(name=null){const clientName=name||activeClients()[0]?.name,c=client(clientName),items=monthItems().filter(x=>x.client===clientName),steph=personMinutes(items,"stephanie"),jen=personMinutes(items,"jennifer"),cs=calcReport(clientName,db.month,"stephanie",steph),cj=calcReport(clientName,db.month,"jennifer",jen),machines=clientName==="Floriane & Max"?items.reduce((a,x)=>a+(x.machines||0),0):0;layout(`<button onclick="go('home')">← Retour</button><h2>Récapitulatif</h2><select onchange="summary(this.value)">${db.clients.map(c=>`<option ${c.name===clientName?"selected":""}>${c.name}</option>`).join("")}</select><div class="card"><h2>${clientName}</h2><p class="small">${c.ref||""} • ${c.phone||""}<br>${c.address||""}</p><table><tr><th>Date</th><th>Arrivée</th><th>Départ</th><th>Durée</th></tr>${items.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${fmtTime(new Date(x.start))}</td><td>${fmtTime(new Date(x.end))}</td><td>${fmtDur(x.duration)}</td></tr>`).join("")}</table><h3>Reports</h3><p>Stéphanie : ${fmtDur(steph)} • report précédent ${fmtReport(cs.carryIn)} • déclarer ${cs.declared}h • report suivant ${reportLabel(cs.carryOut)}</p><p>Jennifer : ${fmtDur(jen)} • report précédent ${fmtReport(cj.carryIn)} • déclarer ${cj.declared}h • report suivant ${reportLabel(cj.carryOut)}</p>${machines?`<p><b>Machines Floriane & Max :</b> ${machines} × ${euros(db.settings.machinePrice)} = ${euros(machines*db.settings.machinePrice)}</p>`:""}</div><button onclick="window.print()" style="width:100%">🖨️ PDF</button>`)}
function payroll(){const names=[...new Set(monthItems().map(x=>x.client))];let totalS=0,totalJ=0,totalSA=0,totalJA=0,totalMachines=0;const rows=names.map(n=>{const c=client(n),items=monthItems().filter(x=>x.client===n),s=personMinutes(items,"stephanie"),j=personMinutes(items,"jennifer"),cs=calcReport(n,db.month,"stephanie",s),cj=calcReport(n,db.month,"jennifer",j),rate=c.rate||16,m=n==="Floriane & Max"?items.reduce((a,x)=>a+(x.machines||0),0):0;totalS+=cs.declared;totalJ+=cj.declared;totalSA+=cs.declared*rate;totalJA+=cj.declared*rate;totalMachines+=m;return`<tr><td>${n}</td><td>${cs.declared}h<br>${euros(cs.declared*rate)}</td><td>${cj.declared}h<br>${euros(cj.declared*rate)}</td><td>${m?euros(m*db.settings.machinePrice):"-"}</td></tr>`}).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Fiche paie globale</h2><div class="card"><p>Stéphanie : <b>${totalS}h</b> soit <b>${euros(totalSA)}</b></p><p>Jennifer : <b>${totalJ}h</b> soit <b>${euros(totalJA)}</b></p><p>Machines Flo & Max : <b>${totalMachines}</b> soit <b>${euros(totalMachines*db.settings.machinePrice)}</b></p><p>Total : <b>${totalS+totalJ}h</b> soit <b>${euros(totalSA+totalJA+totalMachines*db.settings.machinePrice)}</b></p></div><div class="card"><table><tr><th>Client</th><th>Stéphanie</th><th>Jennifer</th><th>Machines</th></tr>${rows}</table></div><button onclick="window.print()" style="width:100%">🖨️ PDF</button>`)}
function planning(){const items=db.planning.filter(p=>p.date?.startsWith(db.month)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));layout(`<button onclick="go('home')">← Retour</button><h2>Planning</h2><button class="big" onclick="planForm()">➕ Ajouter au planning</button><button class="outline" style="width:100%;margin-top:10px" onclick="window.open('${GOOGLE_CALENDAR_URL}','_blank')">📅 Ouvrir Google Agenda</button>${items.map(p=>`<div class="item"><div class="row"><b>${p.client}</b><span class="pill">${p.time}</span></div><div>${fmtDate(p.date)} • ${p.type} • ${p.worker}</div><div class="grid"><button onclick="planForm('${p.id}')">✏️ Modifier</button><button class="stop" onclick="deletePlan('${p.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class='card'>Aucune intervention prévue.</div>"}`)}
function planForm(id=null){const p=id?db.planning.find(x=>x.id===id):{};layout(`<button onclick="go('planning')">← Retour</button><h2>Intervention prévue</h2><input id="pid" type="hidden" value="${p?.id||""}"><label>Client</label><select id="pclient">${activeClients().map(c=>`<option ${p?.client===c.name?"selected":""}>${c.name}</option>`)}</select><label>Date</label><input id="pdate" type="date" value="${p?.date||new Date().toISOString().slice(0,10)}"><label>Heure</label><input id="ptime" type="time" value="${p?.time||"09:00"}"><label>Type</label><select id="ptype"><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option></select><label>Qui</label><select id="pworker"><option value="deux">À deux</option><option value="stephanie">Stéphanie</option><option value="jennifer">Jennifer</option></select><button class="big" onclick="savePlan()">💾 Enregistrer</button>`);if(p?.type)$("#ptype").value=p.type;if(p?.worker)$("#pworker").value=p.worker}
function savePlan(){const id=$("#pid").value,obj={id:id||uid(),client:$("#pclient").value,date:$("#pdate").value,time:$("#ptime").value,type:$("#ptype").value,worker:$("#pworker").value};db.planning=id?db.planning.map(p=>p.id===id?obj:p):[...db.planning,obj];save();go('planning')}
function deletePlan(id){db.planning=db.planning.filter(p=>p.id!==id);save();go('planning')}
function seasonal(){const items=monthItems().filter(x=>x.client==="Floriane & Max"), machines=items.reduce((a,x)=>a+(x.machines||0),0);layout(`<button onclick="go('home')">← Retour</button><h2>Floriane & Max</h2><div class="card notice"><h3>Machines</h3><p>Uniquement ici : <b>${euros(db.settings.machinePrice)}</b> par machine</p><p>Total mois : <b>${machines}</b> machine(s) = <b>${euros(machines*db.settings.machinePrice)}</b></p></div><button class="big" onclick="newIntervention()">➕ Ajouter une intervention / machine</button>${items.map(x=>`<div class="item"><b>${fmtDate(x.date)}</b><p>${fmtDur(x.duration)} ${x.machines?`• ${x.machines} machine(s)`:''}</p><p class="small">${x.note||""}</p></div>`).join("")||"<div class='card'>Aucune intervention ce mois-ci.</div>"}`)}
function settings(){layout(`<button onclick="go('home')">← Retour</button><h2>Réglages</h2><div class="card ok"><h3>Version V5 Pro</h3><p class="small">Machines facturées uniquement à Floriane & Max.</p></div><div class="card"><label>Mois affiché</label><input type="month" value="${db.month}" onchange="db.month=this.value;save();go('home')"><label>Tarif horaire par défaut</label><input type="number" value="${db.settings.hourRate}" onchange="db.settings.hourRate=+this.value;save()"><label>Prix machine Floriane & Max</label><input type="number" step="0.01" value="${db.settings.machinePrice}" onchange="db.settings.machinePrice=+this.value;save()"></div><div class="card"><button class="big" onclick="exportData()">💾 Télécharger la sauvegarde</button><label>Restaurer une sauvegarde</label><input type="file" onchange="importData(event)"></div><div class="card notice"><button class="big" onclick="closeMonth()">🔒 Clôturer le mois</button><button class="outline" style="width:100%;margin-top:10px" onclick="go('reports')">📊 Voir les reports</button></div>`)}
function reports(){const entries=Object.entries(db.closures||{});layout(`<button onclick="go('settings')">← Retour</button><h2>Reports</h2>${entries.length?entries.map(([k,r])=>`<div class="item"><b>${k}</b><p>Réel ${fmtDur(r.raw||0)} • déclaré ${r.declared}h • report ${fmtReport(r.carryOut||0)}</p></div>`).join(""):"<div class='card'>Aucun mois clôturé.</div>"}`)}
function closeMonth(){if(!confirm("Clôturer le mois affiché ?"))return;const names=[...new Set(monthItems().map(x=>x.client))];names.forEach(n=>{const items=monthItems().filter(x=>x.client===n),s=personMinutes(items,"stephanie"),j=personMinutes(items,"jennifer");db.closures[ckey(n,db.month,"stephanie")]={...calcReport(n,db.month,"stephanie",s),raw:s};db.closures[ckey(n,db.month,"jennifer")]={...calcReport(n,db.month,"jennifer",j),raw:j}});save();alert("Mois clôturé. Les reports passeront au mois suivant.")}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sauvegarde_steph_jenny_v5.json";a.click()}
function normalizeImport(x){if(x.clients&&x.interventions)return x;if(x.data&&Array.isArray(x.data)){let n=defaultDB();n.interventions=x.data.map(it=>({id:it.id||uid(),client:it.client||it.name||"Client",worker:it.worker||"deux",type:it.type||"Ménage",machines:it.client==="Floriane & Max"?(+(it.machines||0)):0,note:it.note||"",start:it.start||it.arrival||new Date().toISOString(),end:it.end||it.departure||new Date().toISOString(),date:(it.date||it.start||new Date().toISOString()).slice(0,10),duration:+(it.duration||0)}));return n}return x}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=normalizeImport(JSON.parse(r.result));save();go('home');alert("Sauvegarde restaurée.")}catch(e){alert("Fichier invalide")}};r.readAsText(f)}
render();
if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
